[build]
  functions = "functions"

[[redirects]]
  from = "/api/update-gallery"
  to = "/.netlify/functions/update-gallery"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/functions"]