[build]
  functions = "functions"

[[redirects]]
  from = "/.netlify/functions/update-gallery"
  to = "/.netlify/functions/update-gallery"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"